server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare_auth
    username: healthcare_user
    password: healthcare_password

  logging:
    level:
      com.zaxxer.hikari: DEBUG

  jackson:
    time-zone: Asia/Kolkata

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret: ${JWT_SECRET:}
  expiration: 3600000